### ISSUE TITLE
switch to terraform init -upgrade 

### ISSUE THREAD

**Issue by tim-tschiersch** [adorsys/ops-k8s-bootstrap#20]
https://github.com/adorsys/ops-k8s-bootstrap/blob/1f8a99562fc37889107bd0094e22a5cc1f272a4a/.github/workflows/apply.yml#L19

**Comment by Nebucad** [comment]
**Fehlermeldung**
Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider
│ hashicorp/aws: locked provider registry.terraform.io/hashicorp/aws 4.36.1
│ does not match configured version constraint 4.[38](https://github.com/adorsys/ops-k8s-bootstrap/actions/runs/3461167236/jobs/5778431683#step:4:39).0; must use terraform
│ init -upgrade to allow selection of new versions

**Lösung**
terraform init -upgrade
