### ISSUE TITLE
Remove kubectl gavinbunny Provider and switch to native 

### ISSUE THREAD

**Issue by nce** [adorsys/ops-k8s-bootstrap#28]
Because @jmederer and others frown upon the usage of the gavinbunney/kubectl Provider, we'll switch to native hcl.

All `kubectl_manifest` resources should be replaced, with e.g. with this tool:  https://github.com/sl1pm4t/k2tf
which should do most the lifting.

**Comment by tim-tschiersch** [comment]
new detailed issue has been opened -> https://github.com/adorsys/ops-k8s-bootstrap/issues/43
