### ISSUE TITLE
Create IAM User/Group to manage Account from github actions

### ISSUE THREAD

**Issue by nce** [adorsys/ops-k8s-bootstrap#3]
We want to use gh actions to run terraform on `main` Branch commits.

Therefore we need an iam user/group with certain permissions to access aws.

This tasked should be done once by hand and then stored as credentials in the GH repo.

## User creation
```bash
aws iam create-user --user-name ops-github-kaas
aws iam create-access-key --user-name ops-github-kaas
```

## Credential Setting in Github
In this repo, switch to 'Settings' -> 'Secrets' -> 'Actions'
```
-> AWS_ACCESS_KEY_ID (from above ## User creation)
-> AWS_SECRET_ACCESS_KEY (from above ## User creation)
```

AC:
- [x] Account can call `aws sts get-caller-identity`
- [x] above call is run in github actions

**Comment by tim-tschiersch** [comment]
##policy.yml
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "Stmt1667997895963",
      "Action": [
        "secretsmanager:DescribeSecret",
        "secretsmanager:GetResourcePolicy",
        "secretsmanager:GetSecretValue"
      ],
      "Effect": "Allow",
      "Resource": "arn:aws:secretsmanager:eu-central-1:571075516563:secret:kaas/*"
    }
  ]
}
```

##Command
`aws iam put-user-policy --user-name ops-github-kaas --policy-document file://policy2.yml --policy-name read-secrets-manager 
`
Requires aws profile to be set!

**Comment by nce** [comment]
I've reworked our project setup. We create these kind of modifications now not by hand.

We run terraform on this init.tf file:
https://github.com/adorsys/ops-k8s-bootstrap/blob/5b0d51be59ac1df91d2ba929404ba950eb289d60/init.tf
This file should include everything to setup a new aws account/gh pipelineuser
