### ISSUE TITLE
TFsec Issue with Wildcard in Iam Policy and IAM Policy attachment

### ISSUE THREAD

**Issue by florianbeu** [adorsys/ops-k8s-bootstrap#33]
TFsec is reporting 
`tf.[aws-iam-no-policy-wildcards][HIGH] - IAM policy document uses sensitive action 'route53:ListResourceRecordSets' on wildcarded resource '*'
IAM policy document uses sensitive action 'route53:ListResourceRecordSets' on wildcarded resource '*'`

which is a HIGH Prio finding and needs to be fixed.

and 
`tf.[aws-iam-no-user-attached-policies][LOW] - One or more policies are attached directly to a user
One or more policies are attached directly to a user`

which is a LOW Prio finding and can be ignored

**Comment by tim-tschiersch** [comment]
has been fixed inside an older branch
