### ISSUE TITLE
GH Actions run on all `*-cluster` directories for multicluster use

### ISSUE THREAD

**Issue by nce** [adorsys/ops-k8s-bootstrap#36]
We want to have a few directories defining different clusters:
```
foo-cluster/
bar-cluster/
```

We should "loop" over all this dirs and run terraform on each: https://github.com/adorsys/ops-k8s-bootstrap/blob/18d81d1c391083587b9c85dd251a949840a94a05/.github/workflows/apply.yml#L9

**Comment by nce** [comment]
We need to test this on two(or more) available clusters

**Comment by tim-tschiersch** [comment]
tested with staging & nostalgic-poincare clusters.
