### ISSUE TITLE
DNS for new clusterbootstrapping

### ISSUE THREAD

**Issue by nce** [adorsys/ops-k8s-bootstrap#5]
Each cluster should get access to the one DNS zone of our new `adorsys.io` Domain.
The Domain is bought in the `root` account and then the respective NameserverSection is updated to point to different NS lying in the aws-subaccount.

External DNS needs to have access to this zone and all IAM policies regarding DNSmanagement.

AC:
- [x] a new domain `adorsys.io` is bought
- [x] a new zone is created in a subaccount named `adorsys.io`
- [x] the domain NS section is updated to reflect to the NS of the subaccount zone

**Comment by tim-tschiersch** [comment]
- Created a new zone inside the aws-sandbox, which is called adorsys.io
- Copied the Nameserver from the new zone
- Switched to the root-account and pasted them into the registered domains of the root-zone
