### ISSUE TITLE
Create external-secrets module 

### ISSUE THREAD

**Issue by tim-tschiersch** [adorsys/ops-k8s-bootstrap#54]
We need to implement a service to distribute the imagepull secret in all the namespaces, pulling from our gitlab registry.

I decided to go with https://external-secrets.io/

We should create a `ClusterSecretStore` referencing a path in the aws secretmanager. The .dockerjsonconfig should be put in the AWS SSM by creating it form our new technical user `tech-adorsys-kubermatic`.

```
kubectl create secret docker-registry foobar --docker-server=https://gitlab-regisxxxxxys.de/ --docker-username=ci --docker-password=xxxxx --docker-email=tech-adorsys-kubermatic@adorsys.com --dry-run=client -o yaml
```
Then get the `.data` part and base64 decode it; this should be put in the SSM

The ImagepullSecret for our gitlab registry should only be populated to the namespace if:
```yaml
  namespaceSelector:
    matchLabels:
      git-engine: "gitlab.adorsys"
```

AC:
- [x] Helm Repo is added and deployed
- [x] `ClusterSecretStore` is successfully added
- [x] `ClusterExternalSecret` is added and configured with a namespace selector
- [x] A Secret is populated to a dedicated namespace as imagepullsecret
- [x] The gitlab helloworld demo is deployed and img pulling works

**Comment by nce** [comment]
We've now a working solution; but i'll try to migrate it to an argocd `Application` to reduce our terraform usage.

**Comment by nce** [comment]
I've set the `refreshTime` to `1m` as this is the time we want to wait for a secret to be placed in the NS
