### ISSUE TITLE
Setup externalDNS for cluster dns management

### ISSUE THREAD

**Issue by nce** [adorsys/ops-k8s-bootstrap#6]
Depends on #5

We want to create an IAM User for each cluster. This User should be able to mange the DNS for its cluster `<name>.adorsys.io`.

The AWS credentials should be placed in a kubernetes secret to allow external-dns access to route53.

AC:
- [x] external dns is configured as module in bootstrap
- [x] externaldns is working for the demo cluster
- [x] the iam User can only manage its cluster zone

**Comment by tim-tschiersch** [comment]
- external dns has been configured as module in bootstrap
- externaldns is working for staging-cluster
- the iam User can only manage its own cluster zone
